services:
  - type: web
    name: game-of-asater-api
    env: node
    region: frankfurt
    plan: free
    branch: main
    rootDir: .
    buildCommand: npm install && npm -w @workspace/api-server run build
    startCommand: npm -w @workspace/api-server run start
    healthCheckPath: /api/healthz
    envVars:
      - key: NODE_VERSION
        value: 22
